require "rake/testtask"

Rake::TestTask.new do |t|
  t.description = "Run tests"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: :test

namespace :test do
  desc "Run tests with coverage report"
  task :coverage do
    ENV["COVERAGE"] = "yes"
    Rake::Task["test"].execute
  end
end
